defects/urls.py
from django.conf.urls import url, patterns
from . import views
urlpatterns = [
    url(r'^$',views.index,name="index"),
    url(r'^mydefects$',views.mydefects,name="mydefects"),
    url(r'^moderate$',views.moderate,name="moderate"),
    url(r'^list$',views.list,name="list"),
    url(r'^help$',views.help,name="help"),
    url(r'^rules$',views.rules,name="rules"),
    url(r'^ok$',views.ok,name="ok"),
    url(r'^(?P<issue_id>[0-9]+)$',views.card,name="card"),
    url(r'^(?P<issue_id>[0-9]+)/setSubcontractor$',views.setSubcontractor,name="setSubcontactor"),
    url(r'^(?P<issue_id>[0-9]+)/addComment$',views.addComment,name="addComment"),
    url(r'^(?P<issue_id>[0-9]+)/print$',views.printIssue,name="print"),
    url(r'^(?P<comment_id>[0-9]+)/(?P<issue_id>[0-9]+)/blockcomment$',views.blockcomment,name="blockcomment"),
    url(r'^add$',views.add, name="add"),
    #statuses:
    url(r'^(?P<issue_id>[0-9]+)/unsubscribe$',views.unsubscribe,name="unsubscribe"),#Исполнетель отказался от работ
    url(r'^(?P<issue_id>[0-9]+)/setFix$',views.setFix,name="setFix"),#Заявка виконана
    url(r'^(?P<issue_id>[0-9]+)/setFixModer$',views.setFixModer,name="setFixModer"),#Заявка виконана. Статус выставляэ модератор
    url(r'^(?P<issue_id>[0-9]+)/disapprove',views.disapprove,name="disapprove"),#Заявка відхилена модератором
    url(r'^(?P<issue_id>[0-9]+)/padding',views.padding,name="padding"),#Заявка прийнята виконавце у роботу
    url(r'^(?P<issue_id>[0-9]+)/hold',views.hold,name="hold"),#Заявка утримана(запланована)
    url(r'^(?P<issue_id>[0-9]+)/reopen',views.reopen,name="reopen"),#Заявка переоткрыта
]

news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add$', views.add, name="add"),
    url(r'^$', views.list, name="list"),
    url(r'^(?P<id>[0-9]+)$', views.article, name="article"),
    url(r'^delete/+(?P<id>[0-9]+)$', views.delete, name="delete"),
    url(r'^edit/+(?P<id>[0-9]+)$', views.edit, name="edit"),
    url(r'^publish/+(?P<id>[0-9]+)$', views.publish, name="publish"),
    url(r'^unpublish/+(?P<id>[0-9]+)$', views.unpublish, name="unpublish"),
]

weunion/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from . import views, urls_modules
from ckeditor_uploader import views as viewsck
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin_rm/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^crowdfunding/', include('crowdfunding.urls')),
    url(r'^moderator/$', views.moderator, name="moderator"),
    url(r'^moderator/zvit', views.moderatorsZvit, name="moderatorsZvit"),
    url(r'^towns/+(?P<region_ref>[0-9]+)', views.towns, name="towns"),
    url(r'^choosetown/+(?P<townid>[0-9]+)', views.choosetown, name="choosetown"),
    url(r'^gromadasvillges/+(?P<gromada_id>[0-9]+)', views.gromadasVillages, name="gromadasvillges"),
    url(r'^regions/', views.regions, name="regions"),
    url(r'^gettown', views.gettown, name="gettown"),
    url(r'^about', views.about),
    url(r'^help', views.help),
    url(r'^partners', views.partners),
    url(r'^decentralization', views.decentralization),
    url(r'^contacts',views.contacts),
    url(r'^join',views.join),
    url(r'^api/',include('smartapi.urls', namespace='smartapi')),
    url(r'^rating',views.rating),
    url(r'^rules',views.rules),
    url(r'^test', views.test),
    url(r'^confirmyouremail',views.confirmyouremail),
    url(r'^profile/karma/+(?P<user_id>[0-9]+)',views.karma, name="karma"),
    url(r'^profile/+(?P<user_id>[0-9]+)',views.profile, name="profile"),
    url(r'^profile/userban/+(?P<user_id>[0-9]+)/+(?P<status>[0-9]+)',views.userban, name="userban"),
    url(r'^ckeditor/upload/', viewsck.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(viewsck.browse), name='ckeditor_browse'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':False}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT2, 'show_indexes':False}),
    url(r'^townslivesearch', views.townLiveSearch),
    url(r'^town/(?P<townredirect>.*)$', views.townRedirect),
    url(r'(?P<townslug>[a-z]+)/',include(urls_modules)),
]

defects/models.py
from __future__ import unicode_literals
from django.db import models
#we're going utilize this class
from weunion.models import User, Town, Regions, Subcontractors
from django.core.exceptions import MultipleObjectsReturned

class Attachements(models.Model):
    message_ref = models.ForeignKey('Messages', db_column='message_ref')
    document_ref = models.ForeignKey('Documents', db_column='document_ref')

    class Meta:
        managed = False
        db_table = 'attachements'



class CommentAttachements(models.Model):
    comment_ref = models.ForeignKey('Comments', db_column='comment_ref')
    document_ref = models.ForeignKey('Documents', db_column='document_ref')

    class Meta:
        managed = False
        db_table = 'comment_attachements'


class Comments(models.Model):
    title = models.CharField(max_length=512, blank=True, null=True)
    body = models.CharField(max_length=2048, blank=True, null=True)
    attachements = models.IntegerField()
    issue_ref = models.ForeignKey('Issues', db_column='issue_ref')
    owner_ref = models.ForeignKey(User, db_column='owner_ref', blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)
    block = models.IntegerField()

    class Meta:
        managed = False
        db_table = 'comments'


class Documents(models.Model):
    owner_ref = models.ForeignKey(User, db_column='owner_ref')
    file_ref = models.ForeignKey('Files', db_column='file_ref')
    name = models.CharField(max_length=255)
    file_name = models.CharField(max_length=255)
    type_name = models.CharField(max_length=45)
    size = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'documents'


class Files(models.Model):
    body = models.CharField(max_length=10485760)

    class Meta:
        managed = False
        db_table = 'files'


class IssueFiles(models.Model):
    issue_ref = models.ForeignKey('Issues', db_column='issue_ref')
    document_ref = models.ForeignKey(Documents, db_column='document_ref')

    class Meta:
        managed = False
        db_table = 'issue_files'


class Issues(models.Model):
    owner_ref = models.ForeignKey(User, db_column='owner_ref',verbose_name="Owner")
    parent_task_ref = models.ForeignKey('self', db_column='parent_task_ref')
    status = models.IntegerField()
    assigned_to = models.ForeignKey(Subcontractors, db_column='assigned_to')
    town_ref = models.ForeignKey(Town, db_column='town_ref',verbose_name="Мiсто")
    title = models.CharField(max_length=255,verbose_name="Назва")
    description = models.CharField(max_length=2048,verbose_name="Опис")
    address = models.CharField(max_length=512,verbose_name="Адреса")
    map_lon = models.CharField(max_length=128, blank=True, null=True)
    map_lat = models.CharField(max_length=128, blank=True, null=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'issues'

    #next issue
    def __next(self):
        try:
            return Issues.objects.get(parent_task_ref=self.id)
        except Issues.DoesNotExist:
            return None
        except MultipleObjectsReturned: #TODO: И что это, почему не в импорте ? #not sure yet what to do if there's multiple references which should not be there
            Issues.objects.filter(parent_task_ref=self.id)[0]

    def getTree(self):
        tree=[]
        if(not self.firstIssue()):
            return self.parent_task_ref.getTree()
        tree.append(self)
        issue=self.__next()
        while(issue is not None):
            tree.append(issue)
            issue=issue.__next()
        return tree

    def getFirst(self):
         return self.getTree()[0]


    def last_issue(self):
        return self.getTree()[-1]

    def firstIssue(self):
        try:
            self.parent_task_ref
            return False
        except:
            return True

    #статусы для карточки
    ISSUE_STATUS={"BY_ID":["На модерацii","Вiдкрита","Виконана","Відхилена модератором","Прийнята до виконання","Запланована","Арбiтраж"]}

    def statusName(self):
        return self.ISSUE_STATUS["BY_ID"][self.status]

    def statusNameFirst(self):
        return self.ISSUE_STATUS["BY_ID"][self.getTree()[-1].status]

    def hasComments(self):
        if(self.comments_set.count()>0):
            return True
        else:
            return False

class Messages(models.Model):
    subject = models.CharField(max_length=255, blank=True, null=True)
    text = models.CharField(max_length=2048, blank=True, null=True)
    attachments = models.IntegerField()
    sender_ref = models.ForeignKey(User, related_name='auth_user_sender_ref', db_column='sender_ref')
    rcpt_ref = models.ForeignKey(User, related_name='auth_user_rcpt_ref', db_column='rcpt_ref')
    hidden_sender = models.IntegerField()
    hidden_rcpt = models.IntegerField()
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        managed = False
        db_table = 'messages'

defects/templates/add.html
{% extends 'base.html' %}
{% block title %}Додати заявку на усунення дефекту. Інформаційна система "Розумне місто".{% endblock %}
{% block content %}

    <section class="content-header">
      <h1>
    Додати нову заявку для свого міста - {{ request.user.towns.all.0 }}

      </h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
        <li><a href="../defects/">Дефекти ЖКГ</a></li>
        <li class="active">Додати заявку</li>
      </ol>
</section>


                  <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">

<div class="row">

	<form method="POST" action="../defects/add" name="defectForm" enctype="multipart/form-data" id="addDefect">
        <div class="col-md-5">
		<div class="defectForm-map" id="map" style="width:400px;height:400px;"></div>
</div>
    <div class="col-md-7">
				{% csrf_token %}
    <div class="form-group">
				<label>
					Назва дефекту</label>
					<input class="form-control" type="text" name="title" placeholder="Коротка назва дефекту">
				</div>
    <div class="form-group">
				<label>
					Опис</label>
					<textarea class="form-control" name="description" placeholder="Опишіть докладно проблему"></textarea>
				</div>
<div class="form-group">
				<i class="fa fa-hand-o-left"></i> <label>	Адреса (натисніть по мапі клацанням миші, коліщатком мищі можна збільшити масштаб мапи)	</label>
					<input class="form-control" type="text" name="address" readonly="readonly">
					<input class="form-control" type="hidden" name="map_lat">
					<input type="hidden" name="map_lon">
					<script type="text/javascript">
	    		var map;
				function initMap() {

						map = new google.maps.Map(document.getElementById('map'), {
							center: new google.maps.LatLng({{gmap.lon}},{{gmap.lat}}),
							zoom: {{ gmap.zoom }},
							disableDoubleClickZoom: true
				    	});
				    	var defectMarker = new google.maps.Marker({
							map: map,
							visible: false,
							draggable:true,

						});
				    	google.maps.event.addListener(map, 'click', function(data) {
							defectMarker.setVisible(true);
							defectMarker.setPosition(data['latLng']);
							updateAddress(defectMarker);
						});
						google.maps.event.addListener(defectMarker, 'dragend', function(data) {
							updateAddress(defectMarker);
						});
				}
				function updateAddress(marker){
					$.get("https://maps.googleapis.com/maps/api/geocode/json?&key={{api_key}}&latlng="+marker.position.lat()+","+marker.position.lng()+"&language=uk&sensor=true",function(data){
						if(data.status=="OK"&&data.results.length>0){
							//defectForm.address.value=data.results[0]['address_components'][1]['short_name']+', '+data.results[0]['address_components'][0]['short_name']+', '+data.results[0]['address_components'][2]['short_name']+', '+data.results[0]['address_components'][4]['short_name'];
                            defectForm.address.value=data.results[0].formatted_address;
							defectForm.map_lon.value=marker.position.lng();
							defectForm.map_lat.value=marker.position.lat();
						}
					});
				}
				//thumbs for uploading pictures
				function cardThumb(input){
					if (input.files && input.files[0]) {
						$.each(input.files,function(k,file){
							var reader = new FileReader();

							reader.onload = function (e) {
								var pic_frame = document.createElement("div");
								pic_frame.style["display"]="inline-block";
								pic_frame.classList.add("imageHolder","img-thumbnail");
								var title = document.createElement("div");
								title.innerHTML=file.name;
								title.classList.add("text-success","adidedImgTitle");
								var xFrame = document.createElement("div");
								xFrame.innerHTML="X";
								xFrame.classList.add("btn","btn-danger","btnX");
								xFrame.onclick=function(e){
									e.target.parentNode.remove();
								}
								xFrame.style["display"]="inline";
								xFrame.style["vertical-align"]="top";
								xFrame.style["cursor"]="pointer";
								var pic = new Image();
								pic.src=e.target.result; 
								pic.classList.add("img-responsive","adidedImg");							
								var picture_file = document.createElement("input");
								picture_file.type="hidden";
								picture_file.name="attachements["+file.name+"]";
								picture_file.value=e.target.result;
								
								pic_frame.appendChild(pic);
								pic_frame.appendChild(xFrame);

								pic_frame.appendChild(picture_file);
								thumbHolder.appendChild(pic_frame);
								var files = document.createElement("input");
	             				files.type="hidden";
	              				files.value=file.name;
	              				files.name="files[]";
	              				pic_frame.appendChild(files);
								input.value="";
							}

							reader.readAsDataURL(file);
						});
					}
				}
	    	</script>
			</div>

			<div id="thumbHolder"></div><br/>
		<input type="file" data-buttonText="Виберіть зображення або декілька" class="filestyle" data-badge="false" data-buttonBefore="true" accept="image/*" multiple onchange="cardThumb(this)">
		<div class="defectForm-submit">
            </br>
				 <input class="btn btn-block btn-info" type="submit" value="Додати дефект"  onclick="this.value='Зачекайте, будь ласка...';this.disabled='disabled'; this.form.submit();">
		</div>

		</div>

	</form>
	<script async defer src="https://maps.googleapis.com/maps/api/js?key={{ api_key }}&amp;callback=initMap"></script>
</div>
      </div><!-- /.box-body -->

          </div><!-- /.box -->

        </section><!-- /.content -->

{% endblock %}

defects/templates/index.html
{% extends 'base.html' %}
{% block title %}Заявки на усунення дефектів ЖКГ. Інформаційна система "Розумне місто".{% endblock %}
{% block content %}
     <!-- Main content -->
        <section class="content">
          <!-- Default box -->
          <div class="box">
            <div class="box-body">
                <!-- Карта и статистика -->
                <div class="box">
                    <div class="box-body">
                        <div class="col-md-3">
                            <div class="marg-lable">
                            <h4><span class="label label-warning">{{ defects_open  }}</span> - <a href="?status=1">Відкриті</a></h4>
                            <h4><span class="label label-success">{{ defects_done }}</span> -  <a href="?status=2">Виконані</a></h4>
                            <h4><span class="label label-primary">{{ defects_get }}</span> - <a href="?status=4">У роботі</a></h4>
                            <h4><span class="label label-gray-def">{{ defects_planning }}</span> - <a href="?status=5">Заплановані</a></h4>
                            </div>
                        </div>
            <div class="col-md-9">
<div id="map" style="width: 700px; height: 200px;"></div>
  <script>
      function initMap() {
          //var uluru = {lat: {{ town.map_lon }}, lng: {{ town.map_lat}}};
          var map = new google.maps.Map(document.getElementById('map'), {
              zoom: {{ town.zoom }},
              center: {lat: {{ town.map_lon }}, lng: {{ town.map_lat}}}
          });
          setMarkers(map);
      }


      function setMarkers(map) {
        var infowindow = new google.maps.InfoWindow({
          maxWidth: 160
        });

      var pinOpen = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|f39c12");
      var pinGet = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|3c8dbc");
      var pinPlan = new google.maps.MarkerImage("http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=%E2%80%A2|d2d6de");


        {% for issue in issues.object_list %}
            {% if issue.last_issue.status != 0 and issue.last_issue.status != 3 and issue.last_issue.status != 2 %}
                var marker{{ issue.id }} = new google.maps.Marker({
                  position: {lat: {{issue.map_lat}}, lng: {{issue.map_lon}}},
                  map: map,
                    {% if issue.last_issue.status == 1%}
                        icon: pinOpen,
                    {% elif issue.last_issue.status == 4 %}
                        icon: pinGet,
                    {% elif issue.last_issue.status == 5 %}
                        icon: pinPlan,
                    {% endif %}

                  title: '{{ issue.title }}'
                });

                   var infowindow{{ issue.id }} = new google.maps.InfoWindow({
                    content: "{{ issue.title }}"+
                             "<br/><a href='../defects/{{ issue.id }}'><div class='pull-right'>перейти до заявки</div></a>",

                });

                google.maps.event.addListener(marker{{ issue.id }}, 'click', function() {
                  infowindow{{ issue.id }}.open(map,marker{{ issue.id }});
                });


            {% endif %}
          {%endfor%}
      }

    </script>
                        </div>
                    </div><!-- /.box-body -->
                </div><!-- /.box -->

      <div class="box">
        <div class="box-header with-border"><h3 class="box-title">Заявки на усунення дефектів ЖКГ.
        {% if request.session.statuses %}
            Показуємо тільки:
                    {% if 1 in request.session.statuses %}
                            <span class="label label-warning"><a href="?status=9">Відкриті <i class="fa  fa-times"></i></a> </span>
                    {% elif 2 in request.session.statuses %}
                            <span class="label label-success"><a href="?status=9">Виконані <i class="fa  fa-times"></i></a></span>
                    {% elif 4 in request.session.statuses%}
                            <span class="label label-primary"><a href="?status=9">У роботі <i class="fa  fa-times"></i></a></span>
                    {% elif 5 in request.session.statuses %}
                            <span class="label label-gray-def"> <a href="?status=9">Заплановані <i class="fa  fa-times"></i></a></span>
                    {% endif %}
        {% endif %}
        </h3>
           <div class="pull-right">

                <select id="subcontractors">
                <option value="0">Усі організації</option>
                {% for subcontractor in subcontractor_list %}
                    <option value="{{subcontractor.id}}" {% if request.session.subcontractor == subcontractor.id %} selected="selected" {% endif %}>{{ subcontractor.name }}</option>
                {% endfor %}
                </select>
           </div>



            </div>
                <div class="box-body">
                  <table class="table table-bordered table-hover">
                    <tbody><tr bgcolor="#f4f4f4">
                      <th  style="width: 65px">Ілюстрація</th>
                      <th style="width: 115px">Номер заявки</th>
                      <th>Суть заявки</th>
                      <th style="width: 115px">Статус</th>
                    </tr>

{% for issue in issues.object_list %}
    {% if issue.last_issue.status != 0 and issue.last_issue.status != 3 %}
                <tr>
                    <td class="vert-align">
                        {% if issue.issuefiles_set.all.0.document_ref.type_name == "image" %}
					 <a href="../defects/{{ issue.id  }}" id="defectitem"><img src="/media/defects/thumbnail.{{issue.issuefiles_set.all.0.document_ref.file_name}}"  alt="Зображення дефекту" width="100px" /></a>
                        {% else %}
                            <a href="../defects/{{ issue.id  }}" id="defectitem"><img src="{{ MEDIA_URL }}/defects/empty.gif" width="80px"></a>

					    {% endif %}
                    </td>

                  <td class="vert-align">
                  <a href="../defects/{{ issue.id  }}" id="defectitem">№{{ issue.id }}</a><br/>

                  </td>
                  <td class="valign">
                   <b><a href="../defects/{{ issue.id  }}" id="defectitem">{{issue.title|truncatewords:30}}</a></b><br/>
    	            <i class="fa fa-map-marker"></i>
					<a href="../defects/{{ issue.id  }}" id="defectitem">{{issue.address}}</a>
                  </td>
                  <td class="vert-align">
                    <a href="../defects/{{ issue.id  }}" id="defectitem">
                        {% if issue.last_issue.status == 1 %}
                        <span class="badge bg-yellow">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 2 %}
                        <span class="badge bg-green">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 4 %}
                        <span class="badge bg-aqua">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 5 %}
                        <span class="badge bg-gray">{{issue.last_issue.statusName}}</span>
                        {% else%}
                        <span class="badge bg-gray">{{issue.last_issue.statusName}}</span>
                        {% endif %}
                    </a>
                  </td>

                </tr>
    {% endif %}
            {% endfor %}
              </tbody></table>
            </div>

      {% if issues.paginator.count > 10 %}
    <div class="col-md-12">
<div class="center-block">   {{ issues.render }}</div>
    </div>
{% endif %}
 </div><!-- /.box-body -->

          </div><!-- /.box -->
</div>
        </section><!-- /.content -->
        <script async defer
    src="https://maps.googleapis.com/maps/api/js?key={{api_key}}&callback=initMap">

    </script>
    <script>
    $("#subcontractors").change(function () {
        var a = $('#subcontractors option:selected').val()
        window.location = "?subcontractor="+a;
        console.log('Form has been changed to: '+a)
    });
    </script>
{% endblock %}

defects/templates/mydefects.html
{% extends 'base.html' %}
{% block title %}Ваші заявки на усунення дефектів ЖКГ. Інформаційна система "Розумне місто".{% endblock %}
{% block content %}
 <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">
      <div class="box">
        <div class="box-header with-border"><h3 class="box-title">Заявки на усунення дефектів ЖКГ:</h3></div>
                <div class="box-body">
                  <table class="table table-bordered table-hover">
                    <tbody><tr bgcolor="#f4f4f4">
                      <th  style="width: 65px">Ілюстрація</th>
                      <th style="width: 115px">Номер заявки</th>
                      <th>Суть заявки</th>
                      <th style="width: 115px">Статус</th>
                    </tr>

{% for issue in issues.object_list %}

                <tr>
                    <td class="vert-align">
                        {% if issue.issuefiles_set.all.0.document_ref.type_name == "image" %}
					 <a href="../defects/{{ issue.id  }}" id="defectitem"><img src="/media/defects/thumbnail.{{issue.issuefiles_set.all.0.document_ref.file_name}}"  alt="Зображення дефекту" width="100px" /></a>
                        {% else %}
                            <a href="../defects/{{ issue.id  }}" id="defectitem"><img src="{{ MEDIA_URL }}/defects/empty.gif" width="80px"></a>

					    {% endif %}
                    </td>

                  <td class="vert-align">
                  <a href="../defects/{{ issue.id  }}" id="defectitem">№{{ issue.id }}</a><br/>

                  </td>
                  <td class="valign">
                   <b><a href="../defects/{{ issue.id  }}" id="defectitem">{{issue.title|truncatewords:30}}</a></b><br/>
    	            <i class="fa fa-map-marker"></i>
					<a href="../defects/{{ issue.id  }}" id="defectitem">{{issue.address}}</a>
                  </td>
                  <td class="vert-align">
                      <a href="../defects/{{ issue.id  }}" id="defectitem">
                        {% if issue.last_issue.status == 1 %}
                        <span class="badge bg-yellow">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 2 %}
                        <span class="badge bg-green">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 4 %}
                        <span class="badge bg-aqua">{{issue.last_issue.statusName}}</span>
                        {% elif issue.last_issue.status == 5 %}
                        <span class="badge bg-gray">{{issue.last_issue.statusName}}</span>
                        {% else%}
                        <span class="badge bg-gray">{{issue.last_issue.statusName}}</span>
                        {% endif %}
                    </a>
                  </td>

                </tr>
            {% endfor %}
              </tbody></table>
            </div>

      {% if issues.object_list.count >= 10 %}
    <div class="col-md-12">
<div class="center-block">   {{ issues.render }}</div>
    </div>
{% endif %}
</div><!-- /.box-body -->

          </div><!-- /.box -->

        </section><!-- /.content -->
{% endblock %}

defects/templates/print.html
<section class="content-header">


                  <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">


{% for i in issue.getTree %}
    {% if i.firstIssue %}


           <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Заявка №{{ i.id }}. {{i.title}} </h3>
                </div>
        <div class="box-body">

            <div class="col-md-6">

				<div class="cardOwner"><strong>Додав:</strong> {{i.owner_ref.first_name}} {{issue.owner_ref.last_name}}</div>
			<div class="cardTown"><strong>Місто: </strong>{{i.town_ref}}</div>
			<div class="cardAddress"><strong>Адреса: </strong>
				{{i.address}}
                </div>
    <div class="cardDescr"><strong>Опис заявки:</strong><br/> {{i.description}}</div>


                </div>

                <div class="col-md-6">
				<div class="cardMap">
					<img style="max-width: 100%" src="http://maps.googleapis.com/maps/api/staticmap?center={{issue.map_lat}},{{issue.map_lon}}&amp;zoom=18&amp;size=450x250&amp;markers=color:red|{{issue.map_lat}},{{issue.map_lon}}&amp;sensor=false"></div>
                </div></div></div>

            <div class="box">

                <div class="box-header with-border">
                  <h3 class="box-title">Зображення:</h3>
                </div>
                <div class="box-body">

			{% if i.issuefiles_set.all.0.document_ref.type_name == "image" %}
            <div class="defbox">
				<a href="/media/defects/{{i.issuefiles_set.all.0.document_ref.file_name}}" data-lightbox="card_image" target="_blank">
                    <img class="cardImgItem" src="/media/defects/medium.{{i.issuefiles_set.all.0.document_ref.file_name}}"></a>
			</div>
            {% endif %}



                </div>
        </div>

    {% endif %}


		{% endfor %}

 </div><!-- /.box-body -->

          </div><!-- /.box -->

        </section><!-- /.content -->