mvs_wanted/urls.py
from django.conf.urls import url, patterns
from . import views

urlpatterns = [
    url(r'^$', views.index, name="index"),
    url(r'^category/+(?P<category>[0-9]+)$',views.list,name="list"),
    url(r'^(?P<mvs_wanted_id>[0-9]+)$',views.mvs_wanted,name="mvs_wanted"),
    url(r'^add$', views.add, name="add"),
    url(r'^delete/+(?P<mvs_wanted_id>[0-9]+)$',views.delete,name="delete"),
    url(r'^edit/+(?P<mvs_wanted_id>[0-9]+)$',views.edit,name="edit"),
]

news/urls.py
from django.conf.urls import url
from . import views

urlpatterns = [
    url(r'^add$', views.add, name="add"),
    url(r'^$', views.list, name="list"),
    url(r'^(?P<id>[0-9]+)$', views.article, name="article"),
    url(r'^delete/+(?P<id>[0-9]+)$', views.delete, name="delete"),
    url(r'^edit/+(?P<id>[0-9]+)$', views.edit, name="edit"),
    url(r'^publish/+(?P<id>[0-9]+)$', views.publish, name="publish"),
    url(r'^unpublish/+(?P<id>[0-9]+)$', views.unpublish, name="unpublish"),
]

weunion/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from . import views, urls_modules
from ckeditor_uploader import views as viewsck
from django.views.decorators.cache import cache_page
from django.views.decorators.cache import never_cache

urlpatterns = [
    url(r'^$',views.index, name='index'),
    url(r'^admin_rm/', include(admin.site.urls)),
    url(r'^accounts/', include('allauth.urls')),
    url(r'^crowdfunding/', include('crowdfunding.urls')),
    url(r'^moderator/$', views.moderator, name="moderator"),
    url(r'^moderator/zvit', views.moderatorsZvit, name="moderatorsZvit"),
    url(r'^towns/+(?P<region_ref>[0-9]+)', views.towns, name="towns"),
    url(r'^choosetown/+(?P<townid>[0-9]+)', views.choosetown, name="choosetown"),
    url(r'^gromadasvillges/+(?P<gromada_id>[0-9]+)', views.gromadasVillages, name="gromadasvillges"),
    url(r'^regions/', views.regions, name="regions"),
    url(r'^gettown', views.gettown, name="gettown"),
    url(r'^about', views.about),
    url(r'^help', views.help),
    url(r'^partners', views.partners),
    url(r'^decentralization', views.decentralization),
    url(r'^contacts',views.contacts),
    url(r'^join',views.join),
    url(r'^api/',include('smartapi.urls', namespace='smartapi')),
    url(r'^rating',views.rating),
    url(r'^rules',views.rules),
    url(r'^test', views.test),
    url(r'^confirmyouremail',views.confirmyouremail),
    url(r'^profile/karma/+(?P<user_id>[0-9]+)',views.karma, name="karma"),
    url(r'^profile/+(?P<user_id>[0-9]+)',views.profile, name="profile"),
    url(r'^profile/userban/+(?P<user_id>[0-9]+)/+(?P<status>[0-9]+)',views.userban, name="userban"),
    url(r'^ckeditor/upload/', viewsck.upload, name='ckeditor_upload'),
    url(r'^ckeditor/browse/', never_cache(viewsck.browse), name='ckeditor_browse'),
    url(r'^media/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.MEDIA_ROOT, 'show_indexes':False}),
    url(r'^static/(?P<path>.*)$', 'django.views.static.serve', {'document_root': settings.STATIC_ROOT2, 'show_indexes':False}),
    url(r'^townslivesearch', views.townLiveSearch),
    url(r'^town/(?P<townredirect>.*)$', views.townRedirect),
    url(r'(?P<townslug>[a-z]+)/',include(urls_modules)),
]

mvs_wanted/models.py
from weunion.models import User, Town
import uuid
from stdimage.models import StdImageField
from django.db import models

#генерируем псевдоуникальный файлнейм для загружаемых изображений
def get_file_path(instance, filename):
    ext = filename.split('.')[-1]
    filename = "%s.%s" % (uuid.uuid4(), ext)
    return 'mvs_wanted/%s' % filename


class MvsWanted(models.Model):
    name = models.CharField(max_length=255)
    birth_date = models.DateField()
    image = StdImageField(blank=True, upload_to=get_file_path, variations={
        'large': (600, 400),
        'thumbnail': {"width": 100, "height": 100, "crop": True}
    })
    text = models.CharField(max_length=2000)
    category = models.ForeignKey('MvsWantedCategories', db_column='category_id')
    create_date = models.DateTimeField(auto_now_add=True)
    owner_user = models.ForeignKey(User, db_column='owner_user')
    town = models.ForeignKey(Town, db_column='town')

    class Meta:
        managed = False
        db_table = 'mvs_wanted'


class MvsWantedCategories(models.Model):
    category = models.CharField(max_length=50)

    class Meta:
        managed = False
        db_table = 'mvs_wanted_categories'

mvs_wanted/forms.py
from .models import MvsWanted
from django import forms
from django.forms.extras.widgets import SelectDateWidget

class MvsWantedAdd(forms.ModelForm):
    class Meta:
        model = MvsWanted
        fields = ['category', 'name', 'birth_date','text', 'image']
        widgets = {
            'category': forms.TextInput(attrs={'placeholder': 'Категорія', 'class': 'form-control input-lg'}),
            'name': forms.TextInput(attrs={'placeholder': 'Ім\'я розшукованої особи (максимально 255 символів)',
                                           'class': 'form-control input-lg'}),
            'birth_date': forms.DateInput(
                # format=('%d-%m-%Y'),
                                             attrs={'class':'form-control input-lg',
                                            'placeholder':'Select a date'}),
            'text': forms.Textarea(attrs={'placeholder': 'Інформація про розшукувану особу (максимально 2000 символів)',
                                          'class': 'form-control input-lg'}),
            'image': forms.FileInput(attrs={'class':"filestyle",'data-buttonText': "Виберіть зображення",
                                            'data-badge':"false",'data-buttonBefore':"true"}),
        }

mvs_wanted/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.http import HttpResponse
from .forms import *
from .models import MvsWantedCategories, MvsWanted
from .forms import MvsWantedAdd #используем класс формы для генерации формы добавления
from defects.models import Town, User
from django.core.urlresolvers import reverse
from django.core.exceptions import PermissionDenied
from pure_pagination import Paginator, EmptyPage, PageNotAnInteger

def index(request, townslug):
    categories = MvsWantedCategories.objects.all()
    return render(request, 'mvs_wanted/index.html', {'categories': categories})

def add(request, townslug):
    if(request.user.is_authenticated() and request.user.is_active):
        allowed = request.user.isAllowedToModerate(request.session["town"], 'MvsWanted')
        if allowed:
            categories = MvsWantedCategories.objects.all()
            if request.method == 'POST':
                #вместо модели используем класс формы (а он уже сам работает с моделью+валидирует поля)
                form = MvsWantedAdd(request.POST, request.FILES)
                #fill a model from a POST
                if form.is_valid():
                    user=request.user
                    instance = form.save(commit=False)
                    instance.owner_user = user
                    instance.town = Town.objects.get(id= request.session["town"])
                    instance.image = form.cleaned_data['image']
                    instance.save()
                    return render(request,'mvs_wanted/thank_you.html')
                else:
                    return render(request, 'mvs_wanted/add.html', {'form': form, 'categories': categories})
            else:
                #создаем объект формы
                form = MvsWantedAdd()
                return render(request, 'mvs_wanted/add.html', {'form': form, 'categories': categories})
        else:
            raise PermissionDenied('Досуп заборонено.')
    else:
        redirect('accounts/signup')


def mvs_wanted(request, mvs_wanted_id, townslug):
       mvs_wanted = get_object_or_404(MvsWanted,id=mvs_wanted_id)

       if not (request.session.has_key('town')):
           request.session['town'] = mvs_wanted.town.id
           request.session['town_name'] = mvs_wanted.town.name

       if request.user.is_authenticated():
           allowed = request.user.isAllowedToModerate(mvs_wanted.town.id, 'MvsWanted')
       else:
           allowed = False

       return render(request, 'mvs_wanted/get.html', {'person': mvs_wanted, 'allowed': allowed})


def list(request, category, townslug):
    try:
        page = request.GET.get('page', 1)
    except PageNotAnInteger:
        page = 1

    if 'town' in request.session:
        p = Paginator(MvsWanted.objects.filter(town = request.session["town"], category = category).order_by("-id"), 25, request=request)
        list = p.page(page)
        categoryObject = MvsWantedCategories.objects.get(id = category)
        allowed = request.user.isAllowedToModerate(request.session["town"], 'MvsWanted')

        return render(request, 'mvs_wanted/list.html',{'list': list, 'category': categoryObject, 'allowed': allowed})
    else:
        return redirect(reverse('regions'))


def print(request, mvs_wanted_id, townslug):
    mvs_wanted = get_object_or_404(MvsWanted, id=mvs_wanted_id)

    if request.user.is_authenticated():
        allowed = request.user.isAllowedToModerate(mvs_wanted.town.id, 'MvsWanted')
    else:
        allowed = False

    if allowed:
        return render(request, 'print.html', {'person': mvs_wanted})
    else:
        raise PermissionDenied('Досуп заборонено.')


def delete(request, mvs_wanted_id, townslug):
    mvs_wanted = get_object_or_404(MvsWanted, id=mvs_wanted_id)
    allowed = request.user.isAllowedToModerate(mvs_wanted.town.id, 'MvsWanted')

    if request.user.is_authenticated() and allowed:
        name = mvs_wanted.name
        mvs_wanted.delete()
        return render(request, 'mvs_wanted/deleted.html', {'person': name})
    else:
        raise PermissionDenied('Досуп заборонено.')


def edit(request, mvs_wanted_id, townslug):
    mvs_wanted = get_object_or_404(MvsWanted, id=mvs_wanted_id)
    allowed = request.user.isAllowedToModerate(mvs_wanted.town.id, 'MvsWanted')

    if allowed:
        categories = MvsWantedCategories.objects.all()
        if request.method == 'POST':
            form = MvsWantedAdd(request.POST, request.FILES)
            if form.is_valid():
                user = request.user
                instance = form.save(commit=False)
                instance.id = mvs_wanted_id
                instance.owner_user = user
                instance.town = Town.objects.get(id=request.session["town"])
                instance.image = form.cleaned_data['image']
                instance.save()
                return redirect('../' + mvs_wanted_id)
            else:
                return render(request, 'mvs_wanted/edit.html', {'form': form, 'categories': categories})
        else:
            form = MvsWantedAdd(mvs_wanted.__dict__)
            return render(request, 'mvs_wanted/edit.html', {'form': form, 'categories': categories, 'person': mvs_wanted})
    else:
        raise PermissionDenied('Досуп заборонено.')

mvs_wanted/templates/mvs_wanted/add.html
{% extends 'base.html' %}>

{% block title %} Додати розшукувану особу. Інформаційна система "Розумне місто".{% endblock %}


{% block content %}
<section class="content-header">
      <h1>
    Додати розшукувану особу для міста - {{ request.user.towns.all.0 }}

      </h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
        <li><a href="../mvs_wanted/category/1">Розшукувані особи</a></li>
        <li class="active">Додати</li>
      </ol>
    </section>

        <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">

<div class="col-md-12">

<form id="addMvsWanted" action="../mvs_wanted/add" method="post" enctype="multipart/form-data">
{% csrf_token %}

    <div class="form-group">
     <h4>Категорія</h4>
         <select class="form-control" name="category">
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.category }}</option>
                    {% endfor %}
          </select>
    </div>

    <div class="form-group">
     <h4>Ім'я розшукуваної особи</h4>
	  {{ form.name.errors }}
	  {{ form.name }}
    </div>

    <div class="form-group">
     <h4>Дата народженя</h4>
	  {{ form.birth_date.errors }}
	  {{ form.birth_date }}
    </div>

    <div class="form-group">
        <h4>Інформація про розшукувану особу </h4>
      {{ form.text.errors }}
	  {{ form.text }}<br />
     </div>

    <div class="form-group">
        <h4>Фото </h4>
      {{ form.image.errors }}
	  {{ form.image }}
    </div>


    <div class="col-md-12">

    <div class="text-center"><input type="submit" class="btn btn-primary btn-lg" value="Зберегти"  onclick="this.value='Зачекайте, будь ласка ..';this.disabled='disabled'; this.form.submit();"></div>

    </div>

    </form>

  </div>

          </div>

        </section>
    <script>
{#        $('#id_birth_date').datepicker({#}
{#        dateFormat: 'mm-dd-yy',#}
{#        changeMonth: true,#}
{#        changeYear: true#}
{#    });#}
    </script>

{% endblock %}

mvs_wanted/templates/mvs_wanted/deleted.html
{% extends 'base.html' %}

{% block title %} Запис успішно видалено - {{ person }}. Інформаційна система "Розумне місто".{% endblock %}


{% block content %}
    <section class="content-header">
        <h1>{{ person.category.category }}</h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
            <li><a href="../mvs_wanted/category/1">Розшукувані особи</a></li>
            <li class="active">Перегляд</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->

        <div class="box">
            <div class="box-body">
                <div class="box">

                    <div class="box-header with-border">
                        <h3 class="box-title">Запис успішно видалено - {{ person }}</h3>
                    </div>
                    <div class="box-body">
                        <a href="../mvs_wanted/category/1">Повернутись до списку</a>
                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mvs_wanted/templates/mvs_wanted/edit.html
{% extends 'base.html' %}>

{% block title %} Редагувати запис. Інформаційна система "Розумне місто".{% endblock %}


{% block content %}
<section class="content-header">
      <h1>
    Редагувати запис для міста - {{ request.user.towns.all.0 }}

      </h1>
      <ol class="breadcrumb">
        <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
        <li><a href="../mvs_wanted/category/1">Розшукувані особи</a></li>
        <li class="active">Додати</li>
      </ol>
    </section>

        <!-- Main content -->
        <section class="content">

          <!-- Default box -->
          <div class="box">

            <div class="box-body">

<div class="col-md-12">

<form id="editMvsWanted" action="../edit/{{ person.id }}" method="post" enctype="multipart/form-data">
{% csrf_token %}

    <div class="form-group">
     <h4>Категорія</h4>
         <select class="form-control" name="category" value = {{ person.category_id }}>
                    {% for category in categories %}
                    <option value="{{ category.id }}">{{ category.category }}</option>
                    {% endfor %}
          </select>
    </div>

    <div class="form-group">
     <h4>Ім'я розшукуваної особи</h4>
	  {{ form.name.errors }}
	  {{ form.name }}
    </div>

    <div class="form-group">
     <h4>Дата народженя</h4>
	  {{ form.birth_date.errors }}
	  {{ form.birth_date }}
    </div>

    <div class="form-group">
        <h4>Інформація про розшукувану особу </h4>
      {{ form.text.errors }}
	  {{ form.text }}<br />
     </div>

    <div class="form-group">
        <h4>Фото </h4>
      {{ form.image.errors }}
	  {{ form.image }}
    </div>


    <div class="col-md-12">

    <div class="text-center"><input type="submit" class="btn btn-primary btn-lg" value="Зберегти"  onclick="this.value='Зачекайте, будь ласка ..';this.disabled='disabled'; this.form.submit();"></div>

    </div>

    </form>

  </div>

          </div>
          </div>

        </section>
    <script>
{#        $('#id_birth_date').datepicker({#}
{#        dateFormat: 'mm-dd-yy',#}
{#        changeMonth: true,#}
{#        changeYear: true#}
{#    });#}
    </script>

{% endblock %}

mvs_wanted/templates/mvs_wanted/get.html
{% extends 'base.html' %}

{% block title %} {{ person.name }} - {{ person.category.category }}. Інформаційна система "Розумнемісто".{% endblock %}


{% block content %}
    <section class="content-header">
        <h1>{{ person.category.category }}</h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
            <li><a href="../mvs_wanted/category/{{ person.category.id }}">{{ person.category.category }}</a></li>
            <li class="active">Перегляд</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">

            <div class="box-body">

                {% if allowed %}

                    <div class="col-md-12">

                    <div class="box box-warning">
                        <div class="box-header with-border">
                            <h3 class="box-title">Інструменти модератора:</h3>
                        </div>
                        <div class="box-body">

                            <div class="col-md-2">
                                <a href="#">
                                    <button type="button" data-toggle="modal" data-target="#modal_delete"
                                            class="btn btn-block btn-danger btn-sm"><i class="fa fa-ban"></i> Видалити
                                    </button>
                                </a>

                                <div class="modal fade" tabindex="-1" role="dialog" id="modal_delete">
                                    <div class="modal-dialog">
                                        <div class="modal-content">
                                            <div class="modal-header">
                                                <button type="button" class="close" data-dismiss="modal"
                                                        aria-label="Close"><span
                                                        aria-hidden="true">&times;</span></button>
                                                <h4 class="modal-title">Ви дійсно бажаєте видалити запис?</h4>
                                            </div>

                                            <div class="modal-footer">

                                                <button type="button" class="btn btn-default" data-dismiss="modal">
                                                    Закрити
                                                </button>
                                                <a href="../mvs_wanted/delete/{{ person.id }}">
                                                    <button type="submit" class="btn btn-danger">Видалити запис</button>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>


                            <div class="col-md-2">
                                <a href="../mvs_wanted/edit/{{ person.id }}">
                                    <button type="button" class="btn btn-block btn-info btn-sm">
                                        <i class="fa fa-pencil-square-o"></i> Редагувати
                                    </button>
                                </a>
                            </div>


                            <div class="col-md-2">
                                <a href="../mvs_wanted/print/{{ person.id }}" target="_blank">
                                    <button type="button" class="btn btn-block btn-default btn-sm"><i
                                            class="fa fa-print"></i> Друкувати
                                    </button>
                                </a>
                            </div>

                        </div>
                    </div>
                {% endif %}

                <div class="box">
                    <div class="box-header with-border">
                        <h3 class="box-title">{{ person.name }} </h3>
                        <div class="pull-right">
                            <script type="text/javascript"
                                    src="//s7.addthis.com/js/300/addthis_widget.js#pubid=ra-4f23dc3c4265dc08"></script>
                            <div class="addthis_sharing_toolbox"></div>
                        </div>
                    </div>
                    <div class="box-body">
                        <div class="col-md-7">
                            <p><strong>Дата народженя:</strong> {{ person.birth_date|date:"d.m.Y" }}</p>
                            <p><strong>Інформація:</strong> {{ person.text }}</p>
                            <p><strong>Місто:</strong> <a href="/{{ person.town.slug }}"> {{ person.town.name }}</a></p>
                        </div>

                        <div class="col-md-5">
                            {% if person.image.large %}
                                <a href="{{ person.image.large.url }}" data-lightbox="image-1"
                                   data-title="{{ person.name }}">
                                    <div class="petbox"><img src="{{ person.image.large.url }}" width="100%"></div>
                                </a>
                            {% else %}
                                <div class="petbox"><img src="{{ MEDIA_URL }}/persons/empty.gif" width="100%"></div>
                            {% endif %}
                        </div>
                    </div>
                </div>
    </section><!-- /.content -->


{% endblock %}

mvs_wanted/templates/mvs_wanted/index.html
{% extends 'base.html' %}

{% block title %}{{ category.category }} Інформаційна система "Розумне місто".{% endblock %}
{% load staticfiles %}

{% block content %}

    <section class="content-header">
        <h1>РОЗШУК - Міністерство внутрішніх справ України</h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
            <li class="active">РОЗШУК - Міністерство внутрішніх справ України</li>
        </ol>
    </section>

    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">

            <div class="box-body">
                    <div class="box">
                    <div class="box-body">
                        {% for category in categories %}

                            <div style="margin-bottom: 40px; margin-left: 40px;">
                                <a href="../mvs_wanted/category/{{ category.id }}">
                                    <h3>{{ category.category }}</h3>
                                </a>
                            </div>
                        {% endfor %}

                    </div>
                </div>
            </div>
        </div>
    </section>
{% endblock %}

mvs_wanted/templates/mvs_wanted/list.html
{% extends 'base.html' %}

{% block title %}{{ category.category }} Інформаційна система "Розумне місто".{% endblock %}
{% load staticfiles %}

{% block content %}
    <section class="content-header">
        <h1>{{ category.category }}</h1>
        <ol class="breadcrumb">
            <li><a href="/"><i class="fa fa-home"></i> Головна</a></li>
            <li><a href="../">Розшук</a></li>
            <li class="active">{{ category.category }}</li>
        </ol>
    </section>
    <!-- Main content -->
    <section class="content">

        <!-- Default box -->
        <div class="box">

            <div class="box-body">

                {% if allowed %}

                    <div class="col-md-12">

                        <div class="box box-warning">
                            <div class="box-header with-border">
                                <h3 class="box-title">Інструменти модератора:</h3>
                            </div>
                            <div class="box-body">

                                <div class="col-md-2">
                                    <a href="../add">
                                        <button type="button" class="btn btn-block btn-success btn-sm">
                                            <i class="fa fa-plus"></i> Додати запис
                                        </button>
                                    </a>
                                </div>

                            </div>
                        </div>
                    </div>
                {% endif %}

{#                <div class="box-header with-border"><h3>{{ category.category }}</h3></div>#}

                {% if list.object_list %}

                    <div class="col-md-12">
                    <div class="box-body">
                        {% for person in list.object_list %}
                            <div style="float:left; margin-top: 30px;">
                                {% if person.image.thumbnail %}
                                    <a href="../../mvs_wanted/{{ person.id }}" class="title-person">
                                        <img src="{{ MEDIA_URL }}{{ person.image.thumbnail }}" width="80px">
                                    </a>
                                {% else %}
                                    <a href="../../mvs_wanted/{{ person.id }}" class="title-person"><img
                                            src="{{ MEDIA_URL }}/mvs_wanted/empty.gif" width="80px"></a>
                                {% endif %}
                            </div>
                            <div style="margin-bottom: 60px; margin-left: 100px;">
                                <a href="../../mvs_wanted/{{ person.id }}" class="title-person">
                                    <h3>{{ person.name }}</h3>
                                </a>
                                {{ person.text|truncatewords:25 }}
                            </div>
                        {% endfor %}

                    </div>
                    {% if list.paginator.count > 24 %}
                        <div class="col-md-5 col-md-offset-3">
                            {{ list.render }}
                        </div>
                    {% endif %}
                {% else %}
                    На жаль, для Вашого міста відусутні записи у вибраній категорії
                {% endif %}
                </div>

            </div>
        </div>
    </section>
{% endblock %}

mvs_wanted/templates/mvs_wanted/print.html
   <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">{{ person.name }}</h3>
                </div>
        <div class="box-body">
            <p><strong>Дата народженя:</strong> {{ person.birth_date|date:"d.m.Y" }}</p>
                        <p><strong>Інформація:</strong> {{ person.text }}</p>
                        <p><strong>Місто:</strong> <a href="/{{ person.town.slug }}"> {{ person.town.name }}</a></p>

    <strong>Дата народженя:</strong> {{person.birth_date|date:"d.m.Y" }}<br/>
    <strong>Місто:</strong> {{ person.town.name }}<br/>

               <br/><br/>
           </div>

    </div>


    <div class="box">
                <div class="box-header with-border">
                  <h3 class="box-title">Інформація:</h3>
                </div>
                <div class="box-body">
                {{ person.text }}
                </div>
    </div>


<img src="{{ person.image.large.url }}" width="100%">

mvs_wanted/templates/mvs_wanted/thank_you.html
{% extends 'base.html' %}
{% block title %}Запис додано. Інформаційна система "Розумне місто".{% endblock %}
{% block head_top %}<meta http-equiv="refresh" content="4;url=../mvs_wanted/category/1">{% endblock %}
{% block content %}
 <section class="content">
     <!-- Default box -->
          <div class="box">
                <div class="box-body">
                    <div class="alert alert-success alert-dismissible">
                    <button type="button" class="close" data-dismiss="alert" aria-hidden="true">×</button>
                    <h4><i class="icon fa fa-check"></i> Дякуємо! Ваш запис додано</h4>
                    Дякуємо Вам!
                </div>
          </div><!-- /.box-body -->
          </div><!-- /.box -->
 </section><!-- /.content -->

{% endblock %}